<?php
return array (
      'app' => 'Admin',
      'model' => 'Content',
      'action' => 'default',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '内容管理',
      'icon' => 'th',
      'remark' => '',
      'listorder' => '30',
      'children' => 
      array (
          array (
              'app' => 'Api',
              'model' => 'Guestbookadmin',
              'action' => 'index',
              'data' => '',
              'type' => '1',
              'status' => '1',
              'name' => '所有留言',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
              'children' => 
                  array (
                      array (
                          'app' => 'Api',
                        'model' => 'Guestbookadmin',
                        'action' => 'delete',
                        'data' => '',
                        'type' => '1',
                        'status' => '0',
                        'name' => '删除网站留言',
                        'icon' => '',
                        'remark' => '',
                        'listorder' => '0',
                          ),
                    ),
              ),
              array (
                  'app' => 'Comment',
                  'model' => 'Commentadmin',
                  'action' => 'index',
                  'data' => '',
                  'type' => '1',
                  'status' => '1',
                  'name' => '评论管理',
                  'icon' => '',
                  'remark' => '',
                  'listorder' => '0',
                  'children' => 
                        array (
                          array (
                            'app' => 'Comment',
                            'model' => 'Commentadmin',
                            'action' => 'delete',
                            'data' => '',
                            'type' => '1',
                            'status' => '0',
                            'name' => '删除评论',
                            'icon' => '',
                            'remark' => '',
                            'listorder' => '0',
                           ),
                          array (
                            'app' => 'Comment',
                            'model' => 'Commentadmin',
                            'action' => 'check',
                            'data' => '',
                            'type' => '1',
                            'status' => '0',
                            'name' => '评论审核',
                            'icon' => '',
                            'remark' => '',
                            'listorder' => '0',
                          ),
                     ),
              ),
  ),
);